server:
  port: 9090
  
  
#actuators properties
  
management:  health:    circuitbreakers:      enabled: true
      
  endpoints:
    web:      exposure:        include: health,info,env,metrics
  endpoint:   health:      show-details: always
      
#resilience4j properties


resilience4j:  circuitbreaker:    instances:      productService:
          registerHealthIndicator: true
          eventConsumerBufferSize: 10
          failureRateThreshold: 50
          minimumNumberOfCalls: 5
          automaticTransitionFromOpenToHalfOpenEnabled: true
          waitDurationInOpenState: 5s
          permittedNumberOfCallsInHalfOpenState: 3
          slidingWindowSize : 10
          slidingWindowType : COUNT_BASED
             
  
  retry:    instances:
      productService:
       max-retry-attempts: 5
       wait-duration: 10s      